// Code generated by scripts/generate_openclaw_catalog.go; DO NOT EDIT.
package catalog

type ProviderProfile struct {
	ID             string
	Label          string
	Transport      string
	RequiresAPIKey bool
	RequiresModel  bool
	DefaultAPIBase string
	DefaultModel   string
	APIKeyHeader   string
	APIKeyPrefix   string
	Notes          string
}

type ChannelProfile struct {
	ID               string
	Label            string
	Kind             string
	SupportsInbound  bool
	SupportsOutbound bool
}

var OpenClawProviders = []ProviderProfile{
	{ID: "anthropic", Label: "Anthropic", Transport: "anthropic", RequiresAPIKey: true, RequiresModel: false, DefaultAPIBase: "", DefaultModel: "", APIKeyHeader: "x-api-key", APIKeyPrefix: "", Notes: "Native Anthropic Messages API provider."},
	{ID: "bedrock", Label: "AWS Bedrock (Proxy)", Transport: "openai_compat", RequiresAPIKey: false, RequiresModel: false, DefaultAPIBase: "", DefaultModel: "", APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer ", Notes: "Bedrock via OpenAI-compatible proxy endpoint."},
	{ID: "cerebras", Label: "Cerebras", Transport: "openai_compat", RequiresAPIKey: true, RequiresModel: false, DefaultAPIBase: "https://api.cerebras.ai/v1", DefaultModel: "", APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer ", Notes: "Cerebras OpenAI-compatible endpoint."},
	{ID: "gemini", Label: "Gemini", Transport: "openai_compat", RequiresAPIKey: true, RequiresModel: false, DefaultAPIBase: "https://generativelanguage.googleapis.com/v1beta/openai", DefaultModel: "gemini-3.0-pro", APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer ", Notes: "Gemini OpenAI-compatible endpoint."},
	{ID: "github-copilot", Label: "GitHub Copilot", Transport: "openai_compat", RequiresAPIKey: true, RequiresModel: false, DefaultAPIBase: "", DefaultModel: "", APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer ", Notes: "Copilot OpenAI-compatible endpoint through configured base URL."},
	{ID: "groq", Label: "Groq", Transport: "openai_compat", RequiresAPIKey: true, RequiresModel: false, DefaultAPIBase: "https://api.groq.com/openai/v1", DefaultModel: "", APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer ", Notes: "Groq OpenAI-compatible endpoint."},
	{ID: "huggingface", Label: "Hugging Face", Transport: "openai_compat", RequiresAPIKey: true, RequiresModel: false, DefaultAPIBase: "https://router.huggingface.co/v1", DefaultModel: "", APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer ", Notes: "Hugging Face router OpenAI-compatible endpoint."},
	{ID: "litellm", Label: "LiteLLM", Transport: "openai_compat", RequiresAPIKey: false, RequiresModel: false, DefaultAPIBase: "", DefaultModel: "", APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer ", Notes: "LiteLLM proxy with OpenAI-compatible API."},
	{ID: "lmstudio", Label: "LM Studio", Transport: "openai_compat", RequiresAPIKey: false, RequiresModel: true, DefaultAPIBase: "http://localhost:1234/v1", DefaultModel: "local-model", APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer ", Notes: "Local LM Studio OpenAI-compatible endpoint."},
	{ID: "mistral", Label: "Mistral", Transport: "openai_compat", RequiresAPIKey: true, RequiresModel: false, DefaultAPIBase: "https://api.mistral.ai/v1", DefaultModel: "", APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer ", Notes: "Mistral OpenAI-compatible endpoint."},
	{ID: "ollama", Label: "Ollama", Transport: "openai_compat", RequiresAPIKey: false, RequiresModel: true, DefaultAPIBase: "http://localhost:11434/v1", DefaultModel: "llama3.1:8b", APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer ", Notes: "Local Ollama OpenAI-compatible endpoint."},
	{ID: "openai", Label: "OpenAI", Transport: "openai_compat", RequiresAPIKey: true, RequiresModel: false, DefaultAPIBase: "https://api.openai.com/v1", DefaultModel: "", APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer ", Notes: "OpenAI-compatible provider endpoint."},
	{ID: "openrouter", Label: "OpenRouter", Transport: "openai_compat", RequiresAPIKey: true, RequiresModel: false, DefaultAPIBase: "https://openrouter.ai/api/v1", DefaultModel: "", APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer ", Notes: "OpenRouter OpenAI-compatible endpoint."},
	{ID: "vercel-ai-gateway", Label: "Vercel AI Gateway", Transport: "openai_compat", RequiresAPIKey: true, RequiresModel: false, DefaultAPIBase: "", DefaultModel: "", APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer ", Notes: "Vercel AI Gateway OpenAI-compatible endpoint."},
	{ID: "xai", Label: "xAI", Transport: "openai_compat", RequiresAPIKey: true, RequiresModel: false, DefaultAPIBase: "https://api.x.ai/v1", DefaultModel: "", APIKeyHeader: "Authorization", APIKeyPrefix: "Bearer ", Notes: "xAI OpenAI-compatible endpoint."},
}

var OpenClawChannels = []ChannelProfile{
	{ID: "bluebubbles", Label: "BlueBubbles", Kind: "core", SupportsInbound: true, SupportsOutbound: true},
	{ID: "discord", Label: "Discord", Kind: "core", SupportsInbound: true, SupportsOutbound: true},
	{ID: "feishu", Label: "Feishu", Kind: "plugin", SupportsInbound: true, SupportsOutbound: true},
	{ID: "googlechat", Label: "Google Chat", Kind: "core", SupportsInbound: true, SupportsOutbound: true},
	{ID: "imessage", Label: "iMessage", Kind: "core", SupportsInbound: true, SupportsOutbound: true},
	{ID: "irc", Label: "IRC", Kind: "core", SupportsInbound: true, SupportsOutbound: true},
	{ID: "line", Label: "LINE", Kind: "plugin", SupportsInbound: true, SupportsOutbound: true},
	{ID: "matrix", Label: "Matrix", Kind: "plugin", SupportsInbound: true, SupportsOutbound: true},
	{ID: "mattermost", Label: "Mattermost", Kind: "plugin", SupportsInbound: true, SupportsOutbound: true},
	{ID: "msteams", Label: "Microsoft Teams", Kind: "plugin", SupportsInbound: true, SupportsOutbound: true},
	{ID: "nextcloud", Label: "Nextcloud", Kind: "plugin", SupportsInbound: true, SupportsOutbound: true},
	{ID: "nostr", Label: "Nostr", Kind: "plugin", SupportsInbound: true, SupportsOutbound: true},
	{ID: "signal", Label: "Signal", Kind: "core", SupportsInbound: true, SupportsOutbound: true},
	{ID: "slack", Label: "Slack", Kind: "core", SupportsInbound: true, SupportsOutbound: true},
	{ID: "telegram", Label: "Telegram", Kind: "core", SupportsInbound: true, SupportsOutbound: true},
	{ID: "tlon", Label: "Tlon", Kind: "plugin", SupportsInbound: true, SupportsOutbound: true},
	{ID: "twitch", Label: "Twitch", Kind: "plugin", SupportsInbound: true, SupportsOutbound: true},
	{ID: "webchat", Label: "Web Chat", Kind: "core", SupportsInbound: true, SupportsOutbound: true},
	{ID: "whatsapp", Label: "WhatsApp", Kind: "core", SupportsInbound: true, SupportsOutbound: true},
	{ID: "zalo", Label: "Zalo", Kind: "plugin", SupportsInbound: true, SupportsOutbound: true},
}

func ProviderByID(id string) (ProviderProfile, bool) {
	for _, p := range OpenClawProviders {
		if p.ID == id {
			return p, true
		}
	}
	return ProviderProfile{}, false
}

func ChannelByID(id string) (ChannelProfile, bool) {
	for _, c := range OpenClawChannels {
		if c.ID == id {
			return c, true
		}
	}
	return ChannelProfile{}, false
}
